config/routes.rb
Rails.application.routes.draw do

  get 'tweets/search'

  devise_for :users,:controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: "registrations" }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get 'home', to: 'home#index'
  get 'tweets', to: 'tweets#index'
  root 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  devise :database_authenticatable,
         :registerable, :trackable,
         :omniauthable,:validatable, :omniauth_providers => [:twitter]

  has_one :identity, dependent: :destroy

  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    identity = Identity.find_for_oauth(auth)
    user = signed_in_resource ? signed_in_resource : identity.user
    if user.nil?
      user = User.new(
        name: auth.info.name,
        profile_img_url: auth.info.image.gsub("_normal",""),
        email: "#{TEMP_EMAIL_PREFIX}#{auth.uid}#{auth.provider}.com",
        password: Devise.friendly_token[0,20]
      )
      user.save!
    end
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def has_complete_profile?
    info = ["name", "phone_number", "address", "city", "state", "country"]
    info.all?{|att| !self.attributes[att].empty? } and !self.has_default_email?
  end

  def has_default_email?
    if TEMP_EMAIL_REGEX.match(self.email)
      true
    else
      false
    end
  end

  def missing_attributes
    keys = self.attributes.select{|k,v| v.blank?}.keys
    keys.unshift("email") if self.has_default_email?
    keys
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user

 def finish_signup
   @form_fields = current_user.missing_attributes
   @user = current_user
   if request.patch? && params[:user]
     if @user.update(user_params)
       sign_in(@user, :bypass => true)
       redirect_to root_url, notice: 'Your profile was successfully updated.'
     else
       @show_errors = true
     end
   end
 end

 private
   def set_user
     @user = User.find(params[:id])
   end

   def user_params
     accessible = current_user.missing_attributes
     params.require(:user).permit(accessible)
   end
 end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/users/finish_signup.html.erb
<div class="form-signin">
  <div class="panel panel-default">
    <div class="panel-body">
      <%= form_for(current_user, :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
      <h2 class="text-center form-signin-heading">Complete your profile</h2>
        <% if @show_errors && current_user.errors.any? %>
          <div id="error_explanation">
            <% current_user.errors.full_messages.each do |msg| %>
              <div class="alert alert-danger" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <%= msg %>
              </div>
            <% end %>
          </div>
        <% end %>
        <% @form_fields.each do |field|%>
          <%= f.label field.to_sym, class:"sr-only" %>
          <%= f.text_field field.to_sym, :value => '', class: 'form-control', placeholder: field.to_s.capitalize.humanize %><br>
        <% end %>
        <div class="row">
          <div class="col-xs-6">
            <%= f.submit 'Save', :class => 'btn btn-lg btn-success btn-block' %>
          </div>
          <div class="col-xs-6">
            <%= link_to 'Do it later', home_path, class: 'btn btn-lg btn-default btn-block' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>