config/routes.rb
Rails.application.routes.draw do

  get 'tweets/search'

  devise_for :users,:controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: "registrations" }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get 'home', to: 'home#index'
  get 'tweets', to: 'tweets#index'
  root 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterApp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <!-- <div class="container"> -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">TwitterApp</a>
          </div>
          <div id="navbar" class="collapse navbar-collapse">
            <%= form_for :query, url: tweets_path, method: "get", :html => {:class => "navbar-form navbar-left"} do |f| %>
              <div class="form-group">
                <%= f.text_field :q, placeholder:"#hashtag" , class: "form-control", required: true %>
                <%= f.text_field :location, placeholder:"Location" , class: "form-control", data: {toggle: "tooltip", placement: "bottom" }, title: "Ex: Rio de Janeiro" %>
                <%= f.text_field :since, placeholder:"Since: dd/mm/yyyy", class: "form-control", data: {toggle: "tooltip", placement: "bottom" }, title: "Date 6 to 9 days ago" %>
                <%= f.text_field :until, placeholder:"Until: dd/mm/yyyy", class: "form-control", data: {toggle: "tooltip", placement: "bottom" }, title: "Date 6 to 9 days ago" %>
                <%= f.select(:attitude, [["Positive :)",":)"], ["Negative :(", ":("]], {include_blank: "Attitude"}, {:class=> "form-control"})%>
              </div>
              <%= f.submit "Search on Twitter", class: "btn btn-info" %>
            <% end %>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Signed in as <%= current_user.name %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Edit profile", edit_user_registration_path(current_user) %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
                </ul>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        <!-- </div> -->
      </nav>
    <br>
    <div class="container">
      <%= yield %>
    </div>
  <% else %>
    <%= yield %>
  <% end %>
  </body>
</html>